name: Despliegue Frontend Local

on:
  push:
    branches: [ "develop" ]
    # En caso de tener front y back en el mismo repositorio (monorepo), 
    # Descomentar la siguiente linea:
    # paths:
    #   - 'front/**'

jobs:
  build-and-deploy-front:
    runs-on: self-hosted

    steps:
      - name: 📥 Obtener el código fuente
        uses: actions/checkout@v4

      - name: 🧹 Limpiar instalación previa de pnpm
        run: rm -rf ~/setup-pnpm

      - name: 📦 Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 
          cache: 'pnpm'
          # En caso de que el front esté en una subcarpeta de un monorepo, 
          # descomentar la línea:
          # cache-dependency-path: './front/pnpm-lock.yaml'

      - name: 📦 Instalar dependencias
        # Si está en una subcarpeta, añade 'cd front &&' antes del comando
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Compilar el proyecto (React)
        run: pnpm run build

      - name: 🚀 Desplegar la aplicación
        run: rm -rf /var/www/html/portales/* && cp -r dist/* /var/www/html/portales/